# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

Audio_SPK_Init_bit  = '- bit'
Audio_SPK_Init_samp = '- kHz'
Audio_SPK_Init_vol  = '- / 100'

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(600, 900))
        Form.setMaximumSize(QtCore.QSize(600, 900))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 580, 880))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.Title_AudioSource = QtWidgets.QLabel(self.frame)
        self.Title_AudioSource.setGeometry(QtCore.QRect(20, 20, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Title_AudioSource.setFont(font)
        self.Title_AudioSource.setObjectName("Title_AudioSource")
        self.TBL_AudioSource = QtWidgets.QTableWidget(self.frame)
        self.TBL_AudioSource.setEnabled(True)
        self.TBL_AudioSource.setGeometry(QtCore.QRect(30, 50, 511, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBL_AudioSource.sizePolicy().hasHeightForWidth())
        self.TBL_AudioSource.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TBL_AudioSource.setFont(font)
        self.TBL_AudioSource.setAutoFillBackground(False)
        self.TBL_AudioSource.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TBL_AudioSource.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TBL_AudioSource.setLineWidth(1)
        self.TBL_AudioSource.setMidLineWidth(0)
        self.TBL_AudioSource.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_AudioSource.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_AudioSource.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TBL_AudioSource.setAlternatingRowColors(False)
        self.TBL_AudioSource.setShowGrid(True)
        self.TBL_AudioSource.setGridStyle(QtCore.Qt.SolidLine)
        self.TBL_AudioSource.setWordWrap(False)
        self.TBL_AudioSource.setCornerButtonEnabled(True)
        self.TBL_AudioSource.setRowCount(1)
        self.TBL_AudioSource.setColumnCount(3)
        self.TBL_AudioSource.setObjectName("TBL_AudioSource")
        item = QtWidgets.QTableWidgetItem()
        self.TBL_AudioSource.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.TBL_AudioSource.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_AudioSource.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_AudioSource.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_AudioSource.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        item.setFont(font)
        self.TBL_AudioSource.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_AudioSource.setItem(0, 2, item)
        self.TBL_AudioSource.horizontalHeader().setVisible(True)
        self.TBL_AudioSource.horizontalHeader().setCascadingSectionResizes(False)
        self.TBL_AudioSource.horizontalHeader().setDefaultSectionSize(170)
        self.TBL_AudioSource.horizontalHeader().setHighlightSections(True)
        self.TBL_AudioSource.horizontalHeader().setMinimumSectionSize(36)
        self.TBL_AudioSource.horizontalHeader().setStretchLastSection(False)
        self.TBL_AudioSource.verticalHeader().setVisible(False)
        self.TBL_AudioSource.verticalHeader().setDefaultSectionSize(23)
        self.TBL_AudioSource.verticalHeader().setHighlightSections(False)
        self.TBL_AudioSource.verticalHeader().setMinimumSectionSize(23)
        self.TBL_AudioSource.verticalHeader().setStretchLastSection(True)
        self.Title_AudioPlay = QtWidgets.QLabel(self.frame)
        self.Title_AudioPlay.setGeometry(QtCore.QRect(20, 130, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Title_AudioPlay.setFont(font)
        self.Title_AudioPlay.setObjectName("Title_AudioPlay")
        self.TBL_PlayInfo = QtWidgets.QTableWidget(self.frame)
        self.TBL_PlayInfo.setGeometry(QtCore.QRect(30, 160, 511, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBL_PlayInfo.sizePolicy().hasHeightForWidth())
        self.TBL_PlayInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TBL_PlayInfo.setFont(font)
        self.TBL_PlayInfo.setAutoFillBackground(False)
        self.TBL_PlayInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TBL_PlayInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TBL_PlayInfo.setLineWidth(1)
        self.TBL_PlayInfo.setMidLineWidth(0)
        self.TBL_PlayInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_PlayInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_PlayInfo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TBL_PlayInfo.setAlternatingRowColors(False)
        self.TBL_PlayInfo.setShowGrid(True)
        self.TBL_PlayInfo.setGridStyle(QtCore.Qt.SolidLine)
        self.TBL_PlayInfo.setWordWrap(False)
        self.TBL_PlayInfo.setCornerButtonEnabled(True)
        self.TBL_PlayInfo.setRowCount(1)
        self.TBL_PlayInfo.setColumnCount(3)
        self.TBL_PlayInfo.setObjectName("TBL_PlayInfo")
        item = QtWidgets.QTableWidgetItem()
        self.TBL_PlayInfo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.TBL_PlayInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_PlayInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_PlayInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_PlayInfo.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        item.setFont(font)
        self.TBL_PlayInfo.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_PlayInfo.setItem(0, 2, item)
        self.TBL_PlayInfo.horizontalHeader().setVisible(True)
        self.TBL_PlayInfo.horizontalHeader().setCascadingSectionResizes(False)
        self.TBL_PlayInfo.horizontalHeader().setDefaultSectionSize(170)
        self.TBL_PlayInfo.horizontalHeader().setHighlightSections(True)
        self.TBL_PlayInfo.horizontalHeader().setMinimumSectionSize(36)
        self.TBL_PlayInfo.horizontalHeader().setStretchLastSection(False)
        self.TBL_PlayInfo.verticalHeader().setVisible(False)
        self.TBL_PlayInfo.verticalHeader().setDefaultSectionSize(23)
        self.TBL_PlayInfo.verticalHeader().setHighlightSections(False)
        self.TBL_PlayInfo.verticalHeader().setMinimumSectionSize(23)
        self.TBL_PlayInfo.verticalHeader().setStretchLastSection(True)
        self.TBL_SpkInfo = QtWidgets.QTableWidget(self.frame)
        self.TBL_SpkInfo.setEnabled(True)
        self.TBL_SpkInfo.setGeometry(QtCore.QRect(30, 230, 511, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBL_SpkInfo.sizePolicy().hasHeightForWidth())
        self.TBL_SpkInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TBL_SpkInfo.setFont(font)
        self.TBL_SpkInfo.setAutoFillBackground(False)
        self.TBL_SpkInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TBL_SpkInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TBL_SpkInfo.setLineWidth(1)
        self.TBL_SpkInfo.setMidLineWidth(0)
        self.TBL_SpkInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_SpkInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_SpkInfo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TBL_SpkInfo.setAlternatingRowColors(False)
        self.TBL_SpkInfo.setShowGrid(True)
        self.TBL_SpkInfo.setGridStyle(QtCore.Qt.SolidLine)
        self.TBL_SpkInfo.setWordWrap(False)
        self.TBL_SpkInfo.setCornerButtonEnabled(True)
        self.TBL_SpkInfo.setRowCount(9)
        self.TBL_SpkInfo.setColumnCount(5)
        self.TBL_SpkInfo.setObjectName("TBL_SpkInfo")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.TBL_SpkInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_SpkInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_SpkInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_SpkInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_SpkInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_SpkInfo.setItem(8, 4, item)

        self.TBL_SpkInfo.horizontalHeader().setVisible(True)
        self.TBL_SpkInfo.horizontalHeader().setCascadingSectionResizes(True)
        self.TBL_SpkInfo.horizontalHeader().setDefaultSectionSize(102)
        self.TBL_SpkInfo.horizontalHeader().setHighlightSections(True)
        self.TBL_SpkInfo.horizontalHeader().setMinimumSectionSize(36)
        self.TBL_SpkInfo.horizontalHeader().setStretchLastSection(False)
        self.TBL_SpkInfo.verticalHeader().setVisible(False)
        self.TBL_SpkInfo.verticalHeader().setDefaultSectionSize(23)
        self.TBL_SpkInfo.verticalHeader().setHighlightSections(False)
        self.TBL_SpkInfo.verticalHeader().setMinimumSectionSize(23)
        self.TBL_SpkInfo.verticalHeader().setStretchLastSection(True)
        self.Title_WoW = QtWidgets.QLabel(self.frame)
        self.Title_WoW.setGeometry(QtCore.QRect(20, 490, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Title_WoW.setFont(font)
        self.Title_WoW.setObjectName("Title_WoW")
        self.TBL_WoWPlay = QtWidgets.QTableWidget(self.frame)
        self.TBL_WoWPlay.setGeometry(QtCore.QRect(30, 520, 511, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBL_WoWPlay.sizePolicy().hasHeightForWidth())
        self.TBL_WoWPlay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TBL_WoWPlay.setFont(font)
        self.TBL_WoWPlay.setAutoFillBackground(False)
        self.TBL_WoWPlay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TBL_WoWPlay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TBL_WoWPlay.setLineWidth(1)
        self.TBL_WoWPlay.setMidLineWidth(0)
        self.TBL_WoWPlay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_WoWPlay.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_WoWPlay.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TBL_WoWPlay.setAlternatingRowColors(False)
        self.TBL_WoWPlay.setShowGrid(True)
        self.TBL_WoWPlay.setGridStyle(QtCore.Qt.SolidLine)
        self.TBL_WoWPlay.setWordWrap(False)
        self.TBL_WoWPlay.setCornerButtonEnabled(True)
        self.TBL_WoWPlay.setRowCount(1)
        self.TBL_WoWPlay.setColumnCount(3)
        self.TBL_WoWPlay.setObjectName("TBL_WoWPlay")
        item = QtWidgets.QTableWidgetItem()
        self.TBL_WoWPlay.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.TBL_WoWPlay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_WoWPlay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_WoWPlay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_WoWPlay.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        item.setFont(font)
        self.TBL_WoWPlay.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_WoWPlay.setItem(0, 2, item)
        self.TBL_WoWPlay.horizontalHeader().setVisible(True)
        self.TBL_WoWPlay.horizontalHeader().setCascadingSectionResizes(False)
        self.TBL_WoWPlay.horizontalHeader().setDefaultSectionSize(170)
        self.TBL_WoWPlay.horizontalHeader().setHighlightSections(True)
        self.TBL_WoWPlay.horizontalHeader().setMinimumSectionSize(36)
        self.TBL_WoWPlay.horizontalHeader().setStretchLastSection(False)
        self.TBL_WoWPlay.verticalHeader().setVisible(False)
        self.TBL_WoWPlay.verticalHeader().setDefaultSectionSize(23)
        self.TBL_WoWPlay.verticalHeader().setHighlightSections(False)
        self.TBL_WoWPlay.verticalHeader().setMinimumSectionSize(23)
        self.TBL_WoWPlay.verticalHeader().setStretchLastSection(True)
        self.Title_NWStat = QtWidgets.QLabel(self.frame)
        self.Title_NWStat.setGeometry(QtCore.QRect(20, 600, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Title_NWStat.setFont(font)
        self.Title_NWStat.setObjectName("Title_NWStat")
        self.TBL_NWStat = QtWidgets.QTableWidget(self.frame)
        self.TBL_NWStat.setGeometry(QtCore.QRect(30, 630, 511, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBL_NWStat.sizePolicy().hasHeightForWidth())
        self.TBL_NWStat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TBL_NWStat.setFont(font)
        self.TBL_NWStat.setAutoFillBackground(False)
        self.TBL_NWStat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TBL_NWStat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TBL_NWStat.setLineWidth(1)
        self.TBL_NWStat.setMidLineWidth(0)
        self.TBL_NWStat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_NWStat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TBL_NWStat.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TBL_NWStat.setAlternatingRowColors(False)
        self.TBL_NWStat.setShowGrid(True)
        self.TBL_NWStat.setGridStyle(QtCore.Qt.SolidLine)
        self.TBL_NWStat.setWordWrap(False)
        self.TBL_NWStat.setCornerButtonEnabled(True)
        self.TBL_NWStat.setRowCount(1)
        self.TBL_NWStat.setColumnCount(3)
        self.TBL_NWStat.setObjectName("TBL_NWStat")
        item = QtWidgets.QTableWidgetItem()
        self.TBL_NWStat.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.TBL_NWStat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_NWStat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TBL_NWStat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_NWStat.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        item.setFont(font)
        self.TBL_NWStat.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TBL_NWStat.setItem(0, 2, item)
        self.TBL_NWStat.horizontalHeader().setVisible(True)
        self.TBL_NWStat.horizontalHeader().setCascadingSectionResizes(False)
        self.TBL_NWStat.horizontalHeader().setDefaultSectionSize(170)
        self.TBL_NWStat.horizontalHeader().setHighlightSections(True)
        self.TBL_NWStat.horizontalHeader().setMinimumSectionSize(36)
        self.TBL_NWStat.horizontalHeader().setStretchLastSection(False)
        self.TBL_NWStat.verticalHeader().setVisible(False)
        self.TBL_NWStat.verticalHeader().setDefaultSectionSize(23)
        self.TBL_NWStat.verticalHeader().setHighlightSections(False)
        self.TBL_NWStat.verticalHeader().setMinimumSectionSize(23)
        self.TBL_NWStat.verticalHeader().setStretchLastSection(True)
        self.DebugView = QtWidgets.QTextBrowser(self.frame)
        self.DebugView.setGeometry(QtCore.QRect(30, 711, 511, 161))
        self.DebugView.setObjectName("DebugView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title_AudioSource.setText(_translate("Form", "Audio Source Information"))
        item = self.TBL_AudioSource.verticalHeaderItem(0)
        item.setText(_translate("Form", "Value"))
        item = self.TBL_AudioSource.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Bit depth [bit]"))
        item = self.TBL_AudioSource.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Sampling Rate [kHz]"))
        item = self.TBL_AudioSource.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Audio Channel"))
        __sortingEnabled = self.TBL_AudioSource.isSortingEnabled()
        self.TBL_AudioSource.setSortingEnabled(False)
        item = self.TBL_AudioSource.item(0, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_AudioSource.item(0, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_AudioSource.item(0, 2)
        item.setText(_translate("Form", "-"))
        self.TBL_AudioSource.setSortingEnabled(__sortingEnabled)
        self.Title_AudioPlay.setText(_translate("Form", "Audio Play Information"))
        item = self.TBL_PlayInfo.verticalHeaderItem(0)
        item.setText(_translate("Form", "Value"))
        item = self.TBL_PlayInfo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Channel Configuration"))
        item = self.TBL_PlayInfo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Master Speaker ID"))
        item = self.TBL_PlayInfo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Slave Speaker ID"))
        __sortingEnabled = self.TBL_PlayInfo.isSortingEnabled()
        self.TBL_PlayInfo.setSortingEnabled(False)
        item = self.TBL_PlayInfo.item(0, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_PlayInfo.item(0, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_PlayInfo.item(0, 2)
        item.setText(_translate("Form", "-"))
        self.TBL_PlayInfo.setSortingEnabled(__sortingEnabled)
        item = self.TBL_SpkInfo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Speaker ID"))
        item = self.TBL_SpkInfo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Audio Channel"))
        item = self.TBL_SpkInfo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Bit depth"))
        item = self.TBL_SpkInfo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Sampling Rate"))
        item = self.TBL_SpkInfo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Volume"))
        __sortingEnabled = self.TBL_SpkInfo.isSortingEnabled()
        self.TBL_SpkInfo.setSortingEnabled(False)
        item = self.TBL_SpkInfo.item(0, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(0, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(0, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(0, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(0, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(1, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(1, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(1, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(1, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(1, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(2, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(2, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(2, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(2, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(2, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(3, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(3, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(3, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(3, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(3, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(4, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(4, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(4, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(4, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(4, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(5, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(5, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(5, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(5, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(5, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(6, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(6, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(6, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(6, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(6, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(7, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(7, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(7, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(7, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(7, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))
        item = self.TBL_SpkInfo.item(8, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(8, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_SpkInfo.item(8, 2)
        item.setText(_translate("Form", Audio_SPK_Init_bit))
        item = self.TBL_SpkInfo.item(8, 3)
        item.setText(_translate("Form", Audio_SPK_Init_samp))
        item = self.TBL_SpkInfo.item(8, 4)
        item.setText(_translate("Form", Audio_SPK_Init_vol))

        self.TBL_SpkInfo.setSortingEnabled(__sortingEnabled)
        self.Title_WoW.setText(_translate("Form", "WoWPlay Information"))
        item = self.TBL_WoWPlay.verticalHeaderItem(0)
        item.setText(_translate("Form", "Value"))
        item = self.TBL_WoWPlay.horizontalHeaderItem(0)
        item.setText(_translate("Form", "WowPlay State"))
        item = self.TBL_WoWPlay.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Playback Latency [ms]"))
        item = self.TBL_WoWPlay.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Playback Drop [%]"))
        __sortingEnabled = self.TBL_WoWPlay.isSortingEnabled()
        self.TBL_WoWPlay.setSortingEnabled(False)
        item = self.TBL_WoWPlay.item(0, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_WoWPlay.item(0, 1)
        item.setText(_translate("Form", "-"))
        item = self.TBL_WoWPlay.item(0, 2)
        item.setText(_translate("Form", "- / - / -"))
        self.TBL_WoWPlay.setSortingEnabled(__sortingEnabled)
        self.Title_NWStat.setText(_translate("Form", "Network Status"))
        item = self.TBL_NWStat.verticalHeaderItem(0)
        item.setText(_translate("Form", "Value"))
        item = self.TBL_NWStat.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Wi-Fi Channel"))
        item = self.TBL_NWStat.horizontalHeaderItem(1)
        item.setText(_translate("Form", "RSSI [dBm]"))
        item = self.TBL_NWStat.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Packet Loss [%]"))
        __sortingEnabled = self.TBL_NWStat.isSortingEnabled()
        self.TBL_NWStat.setSortingEnabled(False)
        item = self.TBL_NWStat.item(0, 0)
        item.setText(_translate("Form", "-"))
        item = self.TBL_NWStat.item(0, 1)
        item.setText(_translate("Form", "- / - / -"))
        item = self.TBL_NWStat.item(0, 2)
        item.setText(_translate("Form", "- / - / -"))
        self.TBL_NWStat.setSortingEnabled(__sortingEnabled)


    def Initialize_TBL_UI(self):
        self.Update_AudioSource(Num_Ch='-')
        self.Update_AudioPlay_Config('-','-','-')
        self.Update_WoWPlay(state='-',latency='-',Drop=['-', '-', '-'])
        self.Update_NetworkStat(WiFi_Ch='-',RSSI=['-','-','-'],LossRate=['-','-','-'])

        for row in range(0,9):
            self.Update_AudioPlay_Speaker(row=row, id='-', str_ch='-', bit='-', samp = '-', str_vol='-')


    def Update_AudioSource(self,bit_depth=None,sampling_rate=None,Num_Ch=None):
        if bit_depth is not None:
            txt = "%s bit" % (str(bit_depth))
        else:
            txt = "-"
        item = self.TBL_AudioSource.item(0,0)
        item.setText(txt)

        if sampling_rate is not None:
            txt = "%s kHz" % (str(sampling_rate))
        else:
            txt = "-"
        item = self.TBL_AudioSource.item(0,1)
        item.setText(txt)

        txt = "%s" % (str(Num_Ch))
        item = self.TBL_AudioSource.item(0,2)
        item.setText(txt)


    def Update_AudioPlay_Config(self,CH_CFG=None,Local_CH=None,Wireless_CH=None):
        if CH_CFG is not None:
            item = self.TBL_PlayInfo.item(0,0)
            item.setText( "%s"%(CH_CFG) )

        if Local_CH is not None:
            item = self.TBL_PlayInfo.item(0, 1)
            item.setText("%s"%(Local_CH))

        if Wireless_CH is not None:
            item = self.TBL_PlayInfo.item(0,2)
            item.setText("%s"%(Wireless_CH))


    def Update_WoWPlay(self,state=None,latency=None, Drop=None):
        if state is not None:
            item = self.TBL_WoWPlay.item(0,0)
            item.setText("%s"%(state))

        if latency is not None:
            item = self.TBL_WoWPlay.item(0,1)
            item.setText( "%s"%(str(latency)) )

        if Drop is not None:
            item = self.TBL_WoWPlay.item(0,2)
            item.setText( "%s / %s / %s"%(str(Drop[0]),str(Drop[1]),str(Drop[2])) )


    def Update_NetworkStat(self, WiFi_Ch=None, RSSI=None, LossRate=None):
        if WiFi_Ch is not None:
            item = self.TBL_NWStat.item(0,0)
            item.setText( "%s"%(str(WiFi_Ch)) )

        if RSSI is not None:
            item = self.TBL_NWStat.item(0,1)
            item.setText( "%s / %s / %s"%(str(RSSI[0]),str(RSSI[1]),str(RSSI[2])) )

        if LossRate is not None:
            item = self.TBL_NWStat.item(0,2)
            item.setText( "%s / %s / %s"%(str(LossRate[0]),str(LossRate[1]),str(LossRate[2])) )

    def Update_PrintDebugView(self,log):
        self.DebugView.append(log)

    def Update_AudioPlay_Speaker(self, row=None, id=None, str_ch=None, bit=None, samp = None, str_vol=None):
        if row is None:
            self.Update_PrintDebugView('[AudioPlay_Speaker] row is not configured')
            return

        if id is not None:
            item = self.TBL_SpkInfo.item(row,0)
            item.setText(str(id))

        if str_ch is not None:
            item = self.TBL_SpkInfo.item(row,1)
            item.setText(str_ch)

        if bit is not None:
            item = self.TBL_SpkInfo.item(row,2)
            item.setText(str(bit)+" bit")

        if samp is not None:
            item = self.TBL_SpkInfo.item(row,3)
            item.setText(str(samp)+" kHz")

        if str_vol is not None:
            item = self.TBL_SpkInfo.item(row,4)
            if str_vol is not "Mute":
                item.setText(str_vol+" / 100")
            else:
                item.setText("Mute")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
